### PR TITLE
fixes #13

### LINKED ISSUE #13: required parameter on_delete is missing
python 3.6, django 2.0
```
(gitcoin) kevinowocki@local /Users/kevinowocki/Sites/gitcoin/web/app~ % ./manage.py runserver 0.0.0.0:8080
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10e423d90>
Traceback (most recent call last):
  File "/Users/kevinowocki/code/.virtualenvs/gitcoin/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/kevinowocki/code/.virtualenvs/gitcoin/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 112, in inner_run
    autoreload.raise_last_exception()
  File "/Users/kevinowocki/code/.virtualenvs/gitcoin/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/Users/kevinowocki/code/.virtualenvs/gitcoin/lib/python3.6/site-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/kevinowocki/code/.virtualenvs/gitcoin/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/kevinowocki/code/.virtualenvs/gitcoin/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/kevinowocki/code/.virtualenvs/gitcoin/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/Users/kevinowocki/code/.virtualenvs/gitcoin/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/kevinowocki/code/.virtualenvs/gitcoin/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/kevinowocki/code/.virtualenvs/gitcoin/lib/python3.6/site-packages/sendgrid/models.py", line 23, in <module>
    class Email(models.Model):
  File "/Users/kevinowocki/code/.virtualenvs/gitcoin/lib/python3.6/site-packages/sendgrid/models.py", line 27, in Email
    content_type = models.ForeignKey(ContentType, null=True)
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

### PR DESCRIPTION
**Pull request by owocki**
fixes https://github.com/resmio/django-sendgrid/issues/13

and seems to make everything work in python 3.6, django 2.0

### CODE REVIEW

**Comment by owocki** [comment]
🙌
